server {
    # Puerto 443 para HTTPS (SSL)
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name jsagaro-.42.fr;

    # Rutas de los certificados que creamos en el script
    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

    # Protocolos permitidos por el subject
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}