server {
    # El subject obliga a usar solo el puerto 443 para conexiones seguras
    listen 443 ssl;
    listen [::]:443 ssl;

    # Tu dominio personal (login.42.fr)
    server_name jsagaro-.42.fr;

    # Rutas a tus certificados generados por el script de Bash
    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

    # Restricción obligatoria del subject: solo TLSv1.2 y TLSv1.3
    ssl_protocols TLSv1.2 TLSv1.3;

    # La carpeta compartida (volumen) donde reside WordPress
    root /var/www/html;
    
    # MUY IMPORTANTE: NGINX debe buscar index.php primero
    index index.php index.html index.htm;

    # Comportamiento para enlaces permanentes (permalinks) de WordPress
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # El "puente" hacia el contenedor de WordPress para procesar PHP
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # Aquí es donde ocurre la magia: NGINX le pasa la pelota al contenedor 'wordpress' por el puerto 9000
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
