services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx_image
    restart: always
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - jsagaro-net
    volumes:
      - wordpress_data:/var/www/html

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb_image
    restart: always
    env_file: .env
    networks:
      - jsagaro-net
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress_image
    restart: always
    env_file: .env
    depends_on:
      - mariadb
      - redis
    networks:
      - jsagaro-net
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password

  # ============== BONUS SERVICES ==============

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis_image
    restart: always
    networks:
      - jsagaro-net
    expose:
      - "6379"

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer_image
    restart: always
    depends_on:
      - mariadb
    networks:
      - jsagaro-net
    expose:
      - "8080"

  static:
    container_name: static
    build: ./requirements/bonus/static
    image: static_image
    restart: always
    networks:
      - jsagaro-net
    expose:
      - "80"

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    image: ftp_image
    restart: always
    env_file: .env
    depends_on:
      - wordpress
    networks:
      - jsagaro-net
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - ftp_password

  portainer:
    container_name: portainer
    build: ./requirements/bonus/portainer
    image: portainer_image
    restart: always
    networks:
      - jsagaro-net
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  jsagaro-net:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/portainer
      o: bind

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
